### ISSUE TITLE
Determine how to connect to RSS feeds and what information is sent in a feed

### ISSUE THREAD

**Issue by arushi-g** [nyu-software-engineering/news-aggregator#15]
Especially important is determining if there is a difference in RSS feed content between publications requiring a paid subscription (like The New York Times) and free online content (like Tech Crunch).

**Comment by bloombar** [comment]
This is a spike, not a task.   A task is a piece of work directly related to a specific user story.  Please update all your issues that are mislabeled tasks, when they are in fact spikes - internal tasks that don't directly related to the user stories.
@nyu-software-engineering/spring-2019-news-aggregator

**Comment by arushi-g** [comment]
Will do, thank you!

**Comment by arushi-g** [comment]
RSS feeds appear to be formatted as XML files, and have a standard format across various feed publishers. There is a <channel> item with information about the rss feed, and within that, an <item> for each piece of content on the feed.

**Comment by Himanshi22** [comment]
Please do not leave any task/spike unassigned.
